import type { AdkPrd } from '../agents/schemas';

export function buildPrdBlocks(
  prd: AdkPrd,
  opts: { githubUrl?: string; claudeMention?: string }
): Record<string, unknown>[] {
  const goals = prd.goals.map(g => `• ${g}`).join('\n');
  const stories = prd.userStories.slice(0, 5).map(s => `• ${s}`).join('\n');
  const reqs = prd.functionalRequirements.slice(0, 6).map(r => `• ${r}`).join('\n');
  const ac = prd.acceptanceCriteria.slice(0, 5).map(a => `• ${a}`).join('\n');

  const blocks: Record<string, unknown>[] = [
    {
      type: 'header',
      text: { type: 'plain_text', text: `PRD — ${prd.title}`, emoji: true },
    },
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Problem*\n${prd.problemStatement}`,
      },
    },
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Goals*\n${goals}`,
      },
    },
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*User stories*\n${stories}${prd.userStories.length > 5 ? '\n_…see thread for full list_' : ''}`,
      },
    },
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Requirements*\n${reqs}`,
      },
    },
    {
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Acceptance criteria*\n${ac}`,
      },
    },
  ];

  if (prd.outOfScope?.length) {
    blocks.push({
      type: 'context',
      elements: [
        {
          type: 'mrkdwn',
          text: `*Out of scope:* ${prd.outOfScope.join(' · ')}`,
        },
      ],
    });
  }

  if (prd.openQuestions?.length) {
    blocks.push({
      type: 'context',
      elements: [
        {
          type: 'mrkdwn',
          text: `*Open questions:* ${prd.openQuestions.join(' · ')}`,
        },
      ],
    });
  }

  if (opts.githubUrl) {
    blocks.push({
      type: 'section',
      text: {
        type: 'mrkdwn',
        text: `*Linked GitHub issue:* <${opts.githubUrl}|View issue>`,
      },
    });
  }

  blocks.push({ type: 'divider' });

  const claudeLine = opts.claudeMention
    ? `${opts.claudeMention} ${prd.claudeHandoffPrompt}`
    : prd.claudeHandoffPrompt;

  blocks.push({
    type: 'section',
    text: {
      type: 'mrkdwn',
      text: `*Continue with Claude*\n${claudeLine}`,
    },
  });

  blocks.push({
    type: 'context',
    elements: [
      {
        type: 'mrkdwn',
        text: 'PRD generated by MrSoul · edit in thread or refine with Claude',
      },
    ],
  });

  return blocks;
}

/** Safe PRD → markdown (handles MongoDB plain objects). */
export function formatPrdPlainText(prd: AdkPrd | Record<string, unknown>): string {
  const title = String((prd as AdkPrd).title ?? 'Untitled PRD');
  const problem = String((prd as AdkPrd).problemStatement ?? '');
  const goals = Array.isArray((prd as AdkPrd).goals) ? (prd as AdkPrd).goals : [];
  const stories = Array.isArray((prd as AdkPrd).userStories) ? (prd as AdkPrd).userStories : [];
  const reqs = Array.isArray((prd as AdkPrd).functionalRequirements)
    ? (prd as AdkPrd).functionalRequirements
    : [];
  const ac = Array.isArray((prd as AdkPrd).acceptanceCriteria)
    ? (prd as AdkPrd).acceptanceCriteria
    : [];
  const outOfScope: string[] = Array.isArray((prd as AdkPrd).outOfScope)
    ? ((prd as AdkPrd).outOfScope as string[])
    : [];
  const openQuestions: string[] = Array.isArray((prd as AdkPrd).openQuestions)
    ? ((prd as AdkPrd).openQuestions as string[])
    : [];

  const sections = [
    `# PRD: ${title}`,
    '',
    '## Problem',
    problem,
    '',
    '## Goals',
    ...goals.map(g => `- ${g}`),
    '',
    '## User stories',
    ...stories.map(s => `- ${s}`),
    '',
    '## Functional requirements',
    ...reqs.map(r => `- ${r}`),
    '',
    '## Acceptance criteria',
    ...ac.map(a => `- ${a}`),
  ];
  if (outOfScope.length) {
    sections.push('', '## Out of scope', ...outOfScope.map(o => `- ${o}`));
  }
  if (openQuestions.length) {
    sections.push('', '## Open questions', ...openQuestions.map(q => `- ${q}`));
  }
  return sections.join('\n');
}
